language: "es"

reviews:
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false

  path_filters:
    - "!**/*.lock"
    - "!**/pnpm-lock.yaml"
    - "!**/.next/**"

  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "master"
      - "Development"

  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
    simplify:
      enabled: false

  auto_apply_labels: false
  auto_assign_reviewers: false

chat:
  auto_reply: true
